### ISSUE TITLE
variable %in% names(object@Expectations) is not TRUE

### ISSUE THREAD

**Issue by rosshandler** [PMBio/MOFA#10]
Hi,

 I have been trying to reproduce the example in your R vigenette, but I am getting an error which should be something very simple to fix when running  calculateVarianceExplained(). I just don't see where this error can be. Please could you help me with this issue?

Here is my code (the same as in R vignette essentially):

require(MOFAtools)

data("CLL_data")
MOFAobject <- createMOFAobject(CLL_data)
ModelOptions <- getDefaultModelOpts(MOFAobject)
TrainOptions <- getDefaultTrainOpts()
TrainOptions$maxiter <- 5
MOFAobject <- prepareMOFA(MOFAobject, 
                      DirOptions = DirOptions,
                      ModelOptions = ModelOptions,
                      TrainOptions = TrainOptions
)
r2 <- calculateVarianceExplained(MOFAobject)
Error: variable %in% names(object@Expectations) is not TRUE

**Comment by rargelaguet** [comment]
Hi, you are missing the training model step!
`MOFAobject <- runMOFA(MOFAobject, DirOptions)`

**Comment by rosshandler** [comment]
Thanks a lot for the quick answer!
