### ISSUE TITLE
MOFAtools.rdb corrupt

### ISSUE THREAD

**Issue by whitleyo** [PMBio/MOFA#11]
Hi,

When I try to access the documentation for a function in MOFA, I get an error message saying MOFAtools.rdb is corrupt.

Command in R console in RStudio
> ?calculateVarianceExplained

Error Message:
Error in fetch(key) : 
  lazy-load database '/home/whitleyo/R/x86_64-pc-linux-gnu-library/3.4/MOFAtools/help/MOFAtools.rdb' is corrupt

I tried removing the R package and re-installing

Remove package:
require(ultils)
remove.packages('MOFAtools')

install package again (via R terminal):
devtools::install_github("PMBio/MOFA", subdir="MOFAtools")

I still have same problem after doing this.

Any ideas as to what can be going on?

**Comment by rargelaguet** [comment]
I have never seen this problem... can you remove the .rdb file manually and try to look at the documentation again? Is what this StackOverflow thread suggests: https://stackoverflow.com/questions/30424608/error-in-fetchkey-lazy-load-database

Alternatively, you could try and open MOFAtools.Rproj with Rstudio and compile documentation manually, it should be more explicit about the errors..

**Comment by whitleyo** [comment]
Well, what do you know, restarting the R session got rid of the problem. Sorry about that!

**Comment by rargelaguet** [comment]
the beauty and reproducibility of R :)
