### ISSUE TITLE
FactorBeeswarmPlot uses unnecessary x aesthetic

### ISSUE THREAD

**Issue by DarwinAwardWinner** [PMBio/MOFA#7]
FactorBeesawemPlot uses the "factor" variable as both the x value and the facet. This results in a lot of wasted space if you want to plot multiple factors. I get a better plot by doing something like this:

    FactorBeeswarmPlot(mofaobj, 1:10, color_by = "time_point") + aes(x=0) + xlab("") + facet_wrap(~factor, scales="free") + scale_x_continuous(breaks=NULL)

This removes the irrelevant X scale entirely, puts each factor in its own facet, allows each factor to spread out horizontally throughout its entire facet, and gives each factor its own y scale. The result looks like this:

![image](https://user-images.githubusercontent.com/228145/33689330-e27fff82-da93-11e7-8784-1983a4b9fbc3.png)

**Comment by bv2** [comment]
Thanks a lot for reporting this bug and helping to improve the package!
We removed the unnecessary x axis and incorporated your suggestion in the FactorBeeswarmPlot function.
